### ISSUE TITLE
Part 4 - sidecar.yml token that prevents starts?

### ISSUE THREAD

**Issue by scottdkey** [nigelpoulton/ps-vols-and-pods#2]
Going through the pluralsight course and when trying to load the sidecar I keep getting the error:

`error: error parsing sidecar.yml: error converting YAML to JSON: yaml: line 6: found character that cannot start any token`

Various searching online says that there is an issue with spaces vs tabs in the yaml but I can't figure it out. But there is an issue with the file as it exists in the current project.

**Comment by nigelpoulton** [comment]
Hi @scottdkey 

There was an issue in the sidecar.yml file where spaces had been converted to tabs. This is fixed in the latest PR.

Hope it didn't cause you too many problems!!!
